### ISSUE TITLE
感觉更新到1.48 这界面越来越离谱了啊

### ISSUE THREAD

**Issue by hummingsoul** [nxshell/nxshell#108]
左侧弄个播放按钮干啥的啊 点完没啥反映 再点变成暂停 有时候弹出个框 
保存啥的
nxshell-capture-1635752727675.webm

**Comment by nxshell** [comment]
临时加了个bug录屏工具。。。



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月01日 15:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [nxshell/nxshell] 感觉更新到1.48 这界面越来越离谱了啊 (Issue #108) |

左侧弄个播放按钮干啥的啊 点完没啥反映 再点变成暂停 有时候弹出个框
保存啥的
nxshell-capture-1635752727675.webm

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hummingsoul** [comment]
先不说这位置是不是有点喧宾夺主了 这bug录屏工具我刚用下录bug 也发现bug了啊 录那个下载上传弹出框无法选择目录的bug
这录屏工具根本录不了弹出框 录制完视频 播放到点弹出框 后面就没了

**Comment by nxshell** [comment]
实验性功能，后期会放在合适的位置。。。



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月02日 09:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [nxshell/nxshell] 感觉更新到1.48 这界面越来越离谱了啊 (Issue #108) |

先不说这位置是不是有点喧宾夺主了 这bug录屏工具我刚用下录bug 也发现bug了啊 录那个下载上传弹出框无法选择目录的bug
这录屏工具根本录不了弹出框 录制完视频 播放到点弹出框 后面就没了

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
