### ISSUE TITLE
telnet后切换标签自动产生未知命令

### ISSUE THREAD

**Issue by etanman** [nxshell/nxshell#109]
telnet连接到交换机后，切换标签时，会自动打上一行stty rows 30 columns 101，不知道什么情况。

**Comment by nxshell** [comment]
telnet协议没有窗口resize功能。。。自动加了个命令行工具resize窗口。。。只针对telnet on shell有用



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月02日 00:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [nxshell/nxshell] telnet后切换标签自动产生未知命令 (Issue #109) |

telnet连接到交换机后，切换标签时，会自动打上一行stty rows 30 columns 101，不知道什么情况。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by etanman** [comment]
能不能想办法消除这个显示，很影响体验

**Comment by nxshell** [comment]
telnet目前没有相关的resize功能，需要进一步的解决方案

**Comment by nxshell** [comment]
Fixed in v1.6.5
