### ISSUE TITLE
mac版，最小化后就无法切回来，得退出重新进 m1

### ISSUE THREAD

**Issue by jidaojiuyou** [nxshell/nxshell#111]
m1芯片mac，最小化后就无法切回来，得退出重新进

**Comment by fenyh** [comment]
同样的问题

**Comment by nxshell** [comment]
现在没有Mac测试机，不好意思。只是打了Mac包出来。。。后期如果可能在买个Mac机器测试修复。。。。



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月09日 11:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [nxshell/nxshell] mac版，最小化后就无法切回来，得退出重新进 m1 (Issue #111) |

同样的问题

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nxshell** [comment]
已经fixed， v1.5.2
