### ISSUE TITLE
文件拖拽支持

### ISSUE THREAD

**Issue by azydbly** [nxshell/nxshell#120]
我使用的mac系统的。sftp上传文件只能邮件选择上传然后选择文件，希望支持可以拖拽文件进行上传，现在这种使用规则不方便

**Comment by nxshell** [comment]
记得支持拖拽上传啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年11月21日 13:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [nxshell/nxshell] 文件拖拽支持 (Issue #120) |

我使用的mac系统的。sftp上传文件只能邮件选择上传然后选择文件，希望支持可以拖拽文件进行上传，现在这种使用规则不方便

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bzw1204** [comment]
请更新到最新版本体验！
