### ISSUE TITLE
界面优化建议

### ISSUE THREAD

**Issue by hardyfan** [nxshell/nxshell#128]
1. 可以考虑将左侧的菜单移动顶部；
2. 考虑将左侧的会话列表做成可以隐藏的、可折叠的或者可以弹出可以收起来的；
3. 总之其实是为了显示区域更大一些，最好有全屏切换按钮，可以让操作区全屏起来。

**Comment by nxshell** [comment]
got it



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月02日 19:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [nxshell/nxshell] 界面优化建议 (Issue #128) |

可以考虑将左侧的菜单移动顶部；
考虑将左侧的会话列表做成可以隐藏的、可折叠的或者可以弹出可以收起来的；
总之其实是为了显示区域更大一些，最好有全屏切换按钮，可以让操作区全屏起来。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nxshell** [comment]
已经在v1.5.2版本支持
