### ISSUE TITLE
操作区是否可以全屏

### ISSUE THREAD

**Issue by hardyfan** [nxshell/nxshell#129]
水平方向是很宝贵的，垂直方向是可以上下滚动的。水平方向不能。
左边的主菜单和会话列表区占了太多的宽度，且不可以收起，非常影响操作区的使用。我喜欢大字，但是设置了大字之后，经常要换行显示很难看。

**Comment by nxshell** [comment]
2.0版本会改变工作区空间



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月02日 19:22 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [nxshell/nxshell] 操作区是否可以全屏 (Issue #129) |

水平方向是很宝贵的，垂直方向是可以上下滚动的。水平方向不能。
左边的主菜单和会话列表区占了太多的宽度，且不可以收起，非常影响操作区的使用。我喜欢大字，但是设置了大字之后，经常要换行显示很难看。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nxshell** [comment]
fixed v1.5.2
